# Generated by Django 2.2.24 on 2021-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Meeting Title')),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(verbose_name='Meeting Start time')),
                ('end_time', models.DateTimeField(verbose_name='Meeting End time')),
            ],
        ),
    ]
